### ISSUE TITLE
Install via Composer

### ISSUE THREAD

**Issue by PaulKruijt** [PBXg33k/oauth2-exactonline#6]
When i install via Composer, i get this error:

[InvalidArgumentException]  
  Could not find package pbxg33k/oauth2-exact-provider at any version for your minimum-stability (stabl  
  e). Check the package spelling or your minimum-stability

**Comment by ghost** [comment]
Install first the Oauth2 Client package, update GuzzleHTTP to version 6 and copy the Provider from this Exact-Online Client and paste in the Provider dir from Oauth2 package.... for now the best way... Trial & Error

**Comment by ghost** [comment]
Don't forget the change the namespace !

**Comment by PBXg33k** [comment]
The error message is a pretty generic one, which usually can be surpressed by lowering your minimum-stability from `stable` to `dev`, but i understand that the implications for this change so i've added a tag which SHOULD fix the issue.

Run `composer require pbxg33k/oauth2-exact-provider` to add the latest version to your `composer.json` or manually add `"pbxg33k/oauth2-exact-provider": "^1.0"` to your require.

**Comment by PaulKruijt** [comment]
Thanks for all replies.
But i decided to build a Class myself...a lighter version.

**Comment by ghost** [comment]
@PaulKruijt I am also intrested in your lighter version!  Keep me in Touch
